### ISSUE TITLE
results_per_call and granularity argument for gen_request_parameter() not working in v1.1.1

### ISSUE THREAD

**Issue by erikvansebille** [twitterdev/search-tweets-python#134]
**Describe the bug**

I installed searchtweets v1.1.1 via `pip install searchtweets-v2`. I followed the tutorial in the "Using the Twitter Search APIs’ Python Wrapper" section at https://pypi.org/project/searchtweets-v2/. However, I run into a few errors that are not described in the tutorial. For example, a new keyword `granularity` is now required(?) for `gen_request_parameters()`. However, if I use this I get a HTTP 400 error (see below)

**To Reproduce**

```python
from searchtweets import ResultStream, gen_request_parameters, load_credentials, collect_results
search_args = load_credentials(filename="./twitter_keys.yaml")
query = gen_request_parameters("snow", results_per_call=100)
```
The output is
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-6219d523221c> in <module>
      1 search_args = load_credentials(filename="./twitter_keys.yaml")
      2 
----> 3 query = gen_request_parameters("snow", results_per_call=100)
      4 print(query)
      5 tweets = collect_results(query, max_tweets=10, result_stream_args=search_args)

TypeError: gen_request_parameters() missing 1 required positional argument: 'granularity'
```

If I instead do
```python
from searchtweets import ResultStream, gen_request_parameters, load_credentials, collect_results
search_args = load_credentials(filename="./twitter_keys.yaml")
query = gen_request_parameters("snow", granularity=100)
tweets = collect_results(query, max_tweets=100, result_stream_args=search_args)
```
I get
```
 HTTP Error code: 400: {"errors":[{"parameters":{"granularity":["100"]},"message":"The `granularity` query parameter value [100] is not one of [minute,hour,day]"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"} | Bad Request
 Request payload: {'query': 'snow', 'granularity': 100}
Quitting...
```

**Expected behavior**
Following the tutorial at https://pypi.org/project/searchtweets-v2/, I would expect a `tweets` object  with the result

**Environment**
 - OS: macOS Big Sur
 - Python version 3.8

**Additional context**

**Comment by igorbrigadir** [comment]
As a stopgap, i think setting `granularity=None` should work?

**Comment by erikvansebille** [comment]
Thanks @igorbrigadir, `granularity=None` indeed works!

**Comment by jimmoffitt** [comment]
Thanks @erikvansebille and @igorbrigadir!

I took a look at the code and am now defaulting the new 'granularity' request parameter to None.  

After I check in the code, the `query = gen_request_parameters("snow", results_per_call=100)` line should work as expected.

**Comment by jimmoffitt** [comment]
Checked in updated code... will roll a refreshed package soon!
